[IG]

ig = fsh-generated/resources/ImplementationGuide-fhir.org.nz.ig.base.json
template = https://github.com/HL7NZ/hl7.nz.fhir.template/branches/refined-light-theme
#template = https://github.com/HL7NZ/hl7.nz.fhir.template
apply-version = false
default-version = false


