
id: fhir.org.nz.ig.base
#id: hl7.fhir.nz.base
### experimental!!!  changing the canonical url to match the 
# this is the original   canonical: http://fhir.org.nz/ig/base

canonical: http://hl7.org.nz/ig/base

version: 3.0.1
name: HL7FHIRNewZealandBaseImplementationGuide
title: HL7® FHIR® New Zealand Base Implementation Guide
status: active
publisher:
  name: HL7 New Zealand
  email: mailto:admin@hl7.org.nz
description: New Zealand base profiles
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
  apply-version: false
  # default-version: true
copyrightYear: 2021+
# releaseLabel: Release
releaseLabel: Draft


# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯


# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To control the ig.ini using this config, uncomment and set the "template" property.           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: nzBaseTemplate

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Extensions: extensions.html
  Profiles: profiles.html
  Terminology: terminology.html
  Identifiers: namingSystems.html
  # Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
  # Terminology Audit: termaudit.html
