
id: fhir.org.nz.ig.base
#id: hl7.fhir.nz.base
### experimental!!!  changing the canonical url to match the 
# this is the original   canonical: http://fhir.org.nz/ig/base

canonical: http://hl7.org.nz/fhir

version: 3.1.0
name: HL7FHIRNewZealandBaseImplementationGuide
title: HL7® FHIR® New Zealand Base Implementation Guide
status: active
publisher:
  name: HL7 New Zealand
  email: mailto:admin@hl7.org.nz
description: New Zealand base profiles
license: CC0-1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
# releaseLabel: Release
releaseLabel: Draft


# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯


# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To control the ig.ini using this config, uncomment and set the "template" property.           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: nzBaseTemplate

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Extensions: extensions.html
  Profiles: profiles.html
  Terminology: terminology.html
  Identifiers: namingSystems.html
  # Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
  # Terminology Audit: termaudit.html

parameters:
  show-inherited-invariants: false
  apply-version: false
  # default-version: true
  special-url: 
    - 'https://standards.digital.health.nz/ns/nz-ethnic-group-codes'
    - https://standards.digital.health.nz/ns/acc-patient-occupation-code
    - https://standards.digital.health.nz/ns/alias-type-code
    - https://standards.digital.health.nz/ns/nz-citizenship-status-code
    - https://standards.digital.health.nz/ns/contact-point-purpose-code
    - https://standards.digital.health.nz/ns/coverage-category-code
    - https://standards.digital.health.nz/ns/coverage-type-code
    - https://standards.digital.health.nz/ns/nz-datum-code
    - https://standards.digital.health.nz/ns/dhb-code
    - https://standards.digital.health.nz/ns/domicile-code
    - https://standards.digital.health.nz/ns/ethnic-group-level-4-code
    - https://standards.digital.health.nz/ns/funded-programme-code
    - https://standards.digital.health.nz/ns/hpi-practitioner-role-status-reason-code
    - https://standards.digital.health.nz/ns/information-source-code
    - https://standards.digital.health.nz/ns/iwi-code)
    - https://standards.digital.health.nz/ns/maori-descent-code
    - https://standards.digital.health.nz/ns/nz-residency-code
    - https://standards.digital.health.nz/ns/pho-code
    - https://standards.digital.health.nz/ns/practitioner-additional-authorisation-code
    - https://standards.digital.health.nz/ns/practitioner-registration-status-code
    - https://standards.digital.health.nz/ns/practitioner-scope-of-practice-code)
    - https://standards.digital.health.nz/ns/iwi-code
    - https://standards.digital.health.nz/ns/practitioner-scope-of-practice-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/acc-patient-occupation-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nz-citizenship-status-code
    - (https://nzhts.digital.health.nz/fhir/ValueSet/contact-point-purpose-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/coverage-category-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/coverage-type-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nz-datum-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/dhb-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/dod-information-source-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/domicile-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/ethnic-group-level-4-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nz-ethnic-group-code)
    - https://nzhts.digital.health.nz/fhir/ValueSet/funded-programme-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/hpi-practitioner-role-status-reason-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/information-source-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/iwi-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/alias-type-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/maori-descent
    - https://nzhts.digital.health.nz/fhir/ValueSet/nhi-use-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nz-residency-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/pho-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/practitioner-additional-authorisation-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/practitioner-registration-status-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/practitioner-scope-of-practice-code)
    - https://nzhts.digital.health.nz/fhir/ValueSet/contact-point-purpose-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nz-ethnic-group-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/practitioner-scope-of-practice-code
    - https://nzhts.digital.health.nz/fhir/ValueSet/nzmt-type
