Extension: NzEthnicity
Id: nzEthnicity
Description: "The ethnicity of the patient. Uses level 4 codes (most detailed)."
//These files were generated by a script from a model at NzNHIPatient.ethnicity

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http:/hl7.org.nz/fhir/ValueSet/ethnic-group-level-4 (preferred)